import type {CategoryRule} from "@/types";
import {GROUP_ID_CRITICAL, GROUP_ID_IMPORTANT, GROUP_ID_INCOME, GROUP_ID_OPTIONAL, GROUP_ID_SAVINGS} from "@/constants";

/**
 * Default category rules to be initialized on first app launch
 * These rules provide automatic categorization for common transaction patterns
 */
export const defaultRules: CategoryRule[] = [
    {
        id: 'rule-default-groceries',
        name: 'Shopping - Groceries',
        patterns: [
            {
                field: 'payee',
                matchType: 'wordlist',
                words: ['NOVUS', 'SILPO', 'SELVER', 'KONSUM', 'GROSSI TOIDUKAUBAD', 'RIMI', 'PRISMA', 'NETOMARKET', 'METSA POOD', 'MAKSIMARKET', 'KONSUM', 'LIDL', 'A1000', 'A JA O'].map(text => ({
                    text,
                    negated: false
                })),
                caseSensitive: false,
                weight: 10,
            },
        ],
        patternLogic: 'OR',
        priority: 1,
        type: 'expense',
        groupId: GROUP_ID_CRITICAL,
        colorVariant: 0,
        isDefault: true,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 'rule-default-fast-food',
        name: 'Fast Food',
        patterns: [
            {
                field: 'payee',
                matchType: 'wordlist',
                words: ['MCDONALDS', 'KFC', 'BURGER KING', 'SUBWAY', 'HESBURGER'].map(text => ({text, negated: false})),
                caseSensitive: false,
                weight: 10,
            }
        ],
        patternLogic: 'OR',
        priority: 2,
        type: 'expense',
        groupId: GROUP_ID_OPTIONAL,
        colorVariant: 0,
        isDefault: true,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 'rule-default-restaurants',
        name: 'Restaurants & Cafes',
        patterns: [
            {
                field: 'payee',
                matchType: 'wordlist',
                words: ['RESTAURANT', 'CAFE', 'KOHVIK', 'RESTORAN', 'KAFEANOR', 'LAKOMKA', 'KAVA', 'COFFEE'].map(text => ({
                    text,
                    negated: false
                })),
                caseSensitive: false,
                weight: 8,
            },
            {
                field: 'description',
                matchType: 'wordlist',
                words: ['3bRepublic', 'DUMKA', 'Puzata Khata'].map(text => ({text, negated: false})),
                caseSensitive: false,
                weight: 12,
            },
        ],
        patternLogic: 'OR',
        priority: 2,
        type: 'expense',
        groupId: GROUP_ID_OPTIONAL,
        colorVariant: 1,
        isDefault: true,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 'rule-default-service',
        name: 'Transportation - Service',
        patterns: [
            {
                field: 'payee',
                matchType: 'wordlist',
                words: ['STOP BOX TALLINN', 'AS VIKING MOTORS'].map(text => ({text, negated: false})),
                caseSensitive: false,
                weight: 10,
            },
        ],
        patternLogic: 'OR',
        priority: 1,
        type: 'expense',
        groupId: GROUP_ID_IMPORTANT,
        colorVariant: 6,
        isDefault: true,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 'rule-default-transportation-fuel',
        name: 'Transportation - Fuel',
        patterns: [
            {
                field: 'payee',
                matchType: 'wordlist',
                words: ['AZS', 'WOG', 'ALEXELA', 'HEPA', 'CIRCLE K', 'NESTE', 'OLEREX', 'EUR KLO'].map(text => ({
                    text,
                    negated: false
                })),
                caseSensitive: false,
                weight: 10,
            }
        ],
        patternLogic: 'OR',
        priority: 2,
        type: 'expense',
        groupId: GROUP_ID_IMPORTANT,
        colorVariant: 0,
        isDefault: true,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 'rule-default-transportation-public-transit',
        name: 'Transportation - Public Transit',
        patterns: [
            {
                field: 'payee',
                matchType: 'wordlist',
                words: ['METROPOLITEN', 'METRO', 'BUS', 'TRAM'].map(text => ({text, negated: false})),
                caseSensitive: false,
                weight: 10,
            }
        ],
        patternLogic: 'OR',
        priority: 3, // More specific than general transportation
        type: 'expense',
        groupId: GROUP_ID_IMPORTANT,
        colorVariant: 1,
        isDefault: true,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 'rule-default-shopping-general',
        name: 'Shopping - General',
        patterns: [
            {
                field: 'payee',
                matchType: 'wordlist',
                words: ['SHOPPING', 'MALL', 'STORE', "MAGAZIIN", ' UAmade'].map(text => ({text, negated: false})),
                caseSensitive: false,
                weight: 5,
            },
        ],
        patternLogic: 'OR',
        priority: 1,
        type: 'expense',
        groupId: GROUP_ID_OPTIONAL,
        colorVariant: 2,
        isDefault: true,
        createdAt: new Date(),
        updatedAt: new Date(),
    }, {
        id: 'rule-default-shopping-hobbies',
        name: 'Shopping - Hobbies',
        patterns: [
            {
                field: 'payee',
                matchType: 'wordlist',
                words: ['BOBO',].map(text => ({text, negated: false})),
                caseSensitive: false,
                weight: 5,
            },
        ],
        patternLogic: 'OR',
        priority: 1,
        type: 'expense',
        groupId: GROUP_ID_OPTIONAL,
        colorVariant: 2,
        isDefault: true,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 'rule-default-insurance',
        name: 'Insurance',
        patterns: [
            {
                field: 'payee',
                matchType: 'wordlist',
                words: ['SWEDBANK P&C INSURANCE', 'INSURANCE', 'KINDLUSTUS', 'IIZI'].map(text => ({
                    text,
                    negated: false
                })),
                caseSensitive: false,
                weight: 10,
            },
        ],
        patternLogic: 'OR',
        priority: 2,
        type: 'expense',
        groupId: GROUP_ID_IMPORTANT,
        colorVariant: 2,
        isDefault: true,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 'rule-default-utilities-phone-and-internet',
        name: 'Utilities - Phone & Internet',
        patterns: [
            {
                field: 'payee',
                matchType: 'wordlist',
                words: ['TELE2', 'ELISA', 'TELIA', 'KYIVSTAR', 'VODAFONE', 'T-MOBILE'].map(text => ({
                    text,
                    negated: false
                })),
                caseSensitive: false,
                weight: 10,
            },
        ],
        patternLogic: 'OR',
        priority: 2,
        type: 'expense',
        groupId: GROUP_ID_CRITICAL,
        colorVariant: 1,
        isDefault: true,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 'rule-default-utilities-municipal',
        name: 'Utilities - Municipal',
        patterns: [
            {
                field: 'payee',
                matchType: 'wordlist',
                words: ['TALLINNA LINNAKANTSELEI', 'CITY OF TALLINN'].map(text => ({text, negated: false})),
                caseSensitive: false,
                weight: 10,
            },
        ],
        patternLogic: 'OR',
        priority: 2,
        type: 'expense',
        groupId: GROUP_ID_CRITICAL,
        colorVariant: 2,
        isDefault: true,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 'rule-default-housing',
        name: 'Housing',
        patterns: [
            {
                field: 'payee',
                matchType: 'regex',
                regex: 'MUSTAMÄE TEE.*KÜ|apartment|rent|üür|korteriühistu',
                regexFlags: 'i',
                weight: 10,
            },
        ],
        patternLogic: 'OR',
        priority: 2,
        type: 'expense',
        groupId: GROUP_ID_CRITICAL,
        colorVariant: 3,
        isDefault: true,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 'rule-default-personal-care',
        name: 'Personal Care',
        patterns: [
            {
                field: 'payee',
                matchType: 'wordlist',
                words: ['BARBER', 'SALON', 'JUUKSUR', 'MANIKÜÜR', 'PEDIKÜÜR'].map(text => ({text, negated: false})),
                caseSensitive: false,
                weight: 8,
            }
        ],
        patternLogic: 'OR',
        priority: 2,
        type: 'expense',
        groupId: GROUP_ID_OPTIONAL,
        colorVariant: 3,
        isDefault: true,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 'rule-default-investments-savings',
        name: 'Investments - Savings',
        patterns: [
            {
                field: 'description',
                matchType: 'wordlist',
                words: ['Rahakogujasse', 'save'].map(text => ({text, negated: false})),
                caseSensitive: false,
                weight: 10,
            },
            {
                field: 'description',
                matchType: 'regex',
                regex: 'Fondi.*investeerimine|Mikroinvesteerimine|SWEDBANK ROBUR',
                regexFlags: 'i',
                weight: 12,
            },
        ],
        patternLogic: 'OR',
        priority: 2,
        type: 'expense',
        groupId: GROUP_ID_SAVINGS,
        colorVariant: 0,
        isDefault: true,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 'rule-default-loans-and-credit',
        name: 'Loans & Credit',
        patterns: [
            {
                field: 'description',
                matchType: 'regex',
                regex: 'Laenu põhiosa|loan|intress',
                regexFlags: 'i',
                weight: 10,
            },
        ],
        patternLogic: 'OR',
        priority: 2,
        type: 'expense',
        groupId: GROUP_ID_IMPORTANT,
        colorVariant: 3,
        isDefault: true,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 'rule-default-pension-contributions',
        name: 'Pension Contributions',
        patterns: [
            {
                field: 'payee',
                matchType: 'wordlist',
                words: ['PENSIONIKESKUS', 'PENSION'].map(text => ({text, negated: false})),
                caseSensitive: false,
                weight: 10,
            },
        ],
        patternLogic: 'OR',
        priority: 2,
        type: 'expense',
        groupId: GROUP_ID_SAVINGS,
        colorVariant: 1,
        isDefault: true,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 'rule-default-salary-and-income',
        name: 'Salary & Income',
        patterns: [
            {
                field: 'payee',
                matchType: 'wordlist',
                words: ['SOTSIAALKINDLUSTUSAMET'].map(text => ({text, negated: false})),
                caseSensitive: false,
                weight: 15,
            },
            {
                field: 'description',
                matchType: 'wordlist',
                words: ['salary', 'wage', 'palk', 'hüvitamine'].map(text => ({text, negated: false})),
                caseSensitive: false,
                weight: 10,
            },
        ],
        patternLogic: 'OR',
        priority: 3,
        type: 'income',
        groupId: GROUP_ID_INCOME,
        colorVariant: 0,
        isDefault: true,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 'rule-default-refunds',
        name: 'Refunds',
        patterns: [
            {
                field: 'description',
                matchType: 'wordlist',
                words: ['Refund', 'tagastus', 'return'].map(text => ({text, negated: false})),
                caseSensitive: false,
                weight: 10,
            },
        ],
        patternLogic: 'OR',
        priority: 2,
        type: 'income',
        groupId: GROUP_ID_INCOME,
        colorVariant: 1,
        isDefault: true,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 'rule-default-utilities-electricity',
        name: 'Utilities - Electricity',
        patterns: [
            {
                field: 'payee',
                matchType: 'wordlist',
                words: ['ENEFIT AS', 'ENEFIT', "EESTI ENERGIA"].map(text => ({text, negated: false})),
                caseSensitive: false,
                weight: 10,
            },
        ],
        patternLogic: 'OR',
        priority: 2,
        type: 'expense',
        groupId: GROUP_ID_CRITICAL,
        colorVariant: 4,
        isDefault: true,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 'rule-default-utilities-gas',
        name: 'Utilities - Gas',
        patterns: [
            {
                field: 'payee',
                matchType: 'wordlist',
                words: ['PROPAAN'].map(text => ({text, negated: false})),
                caseSensitive: false,
                weight: 10,
            },
            {
                field: 'description',
                matchType: 'wordlist',
                words: ['propane', 'gas'].map(text => ({text, negated: false})),
                caseSensitive: false,
                weight: 8,
            },
        ],
        patternLogic: 'OR',
        priority: 2,
        type: 'expense',
        groupId: GROUP_ID_CRITICAL,
        colorVariant: 5,
        isDefault: true,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 'rule-default-waste-disposal',
        name: 'Waste Disposal',
        patterns: [
            {
                field: 'payee',
                matchType: 'wordlist',
                words: ['JAATMEJAAM', 'JÄÄTMEJAAM'].map(text => ({text, negated: false})),
                caseSensitive: false,
                weight: 10,
            },
        ],
        patternLogic: 'OR',
        priority: 2,
        type: 'expense',
        groupId: GROUP_ID_CRITICAL,
        colorVariant: 6,
        isDefault: true,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 'rule-default-car-leasing',
        name: 'Car Leasing',
        patterns: [
            {
                field: 'payee',
                matchType: 'wordlist',
                words: ['SWEDBANK LIISING AS', 'LIISING', 'LEASE'].map(text => ({text, negated: false})),
                caseSensitive: false,
                weight: 10,
            },
        ],
        patternLogic: 'OR',
        priority: 2,
        type: 'expense',
        groupId: GROUP_ID_IMPORTANT,
        colorVariant: 4,
        isDefault: true,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 'rule-default-home-improvement',
        name: 'Home Improvement',
        patterns: [
            {
                field: 'payee',
                matchType: 'wordlist',
                words: ['BAUHOF', 'HORTES', 'HANDYMANN', 'BAUHAUS', 'K-RAUTA', 'DECORA'].map(text => ({
                    text,
                    negated: false
                })),
                caseSensitive: false,
                weight: 10,
            },
        ],
        patternLogic: 'OR',
        priority: 2,
        type: 'expense',
        groupId: GROUP_ID_IMPORTANT,
        colorVariant: 5,
        isDefault: true,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 'rule-default-healthcare-dental',
        name: 'Healthcare - Dental',
        patterns: [
            {
                field: 'payee',
                matchType: 'wordlist',
                words: ['HANZADENT', 'DENTAL', 'HAMBAARST'].map(text => ({text, negated: false})),
                caseSensitive: false,
                weight: 10,
            },
        ],
        patternLogic: 'OR',
        priority: 2,
        type: 'expense',
        groupId: GROUP_ID_IMPORTANT,
        colorVariant: 6,
        isDefault: true,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 'rule-default-pharmacies',
        name: 'Healthcare - pharmacies',
        patterns: [
            {
                field: 'payee',
                matchType: 'wordlist',
                words: ['APTEEK', 'PHARMACY'].map(text => ({text, negated: false})),
                caseSensitive: false,
                weight: 10,
            },
        ],
        patternLogic: 'OR',
        priority: 2,
        type: 'expense',
        groupId: GROUP_ID_IMPORTANT,
        colorVariant: 7,
        isDefault: true,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 'rule-default-government-fees',
        name: 'Government Fees',
        patterns: [
            {
                field: 'payee',
                matchType: 'wordlist',
                words: ['RAHANDUSMINISTEERIUM', 'GOVERNMENT', 'TAX OFFICE', 'MAKSU- JA TOLLIAMET', 'TOLL'].map(text => ({
                    text,
                    negated: false
                })),
                caseSensitive: false,
                weight: 10,
            },
        ],
        patternLogic: 'OR',
        priority: 2,
        type: 'expense',
        groupId: GROUP_ID_IMPORTANT,
        colorVariant: 8,
        isDefault: true,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 'rule-default-children-sports-and-activities',
        name: 'Children - Sports & Activities',
        patterns: [
            {
                field: 'payee',
                matchType: 'wordlist',
                words: ['SPORDIKULTUUR', 'SPORTS CLUB', 'LOGOSERV', 'PROGEPISIK OÜ'].map(text => ({
                    text,
                    negated: false
                })),
                caseSensitive: false,
                weight: 10,
            },
        ],
        patternLogic: 'OR',
        priority: 2,
        type: 'expense',
        groupId: GROUP_ID_IMPORTANT,
        colorVariant: 9,
        isDefault: true,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 'rule-default-healthcare-spa-and-wellness',
        name: 'Healthcare - Spa & Wellness',
        patterns: [
            {
                field: 'payee',
                matchType: 'wordlist',
                words: ['ELAMUSSPA', 'SPA', 'WELLNESS'].map(text => ({text, negated: false})),
                caseSensitive: false,
                weight: 10,
            },
        ],
        patternLogic: 'OR',
        priority: 2,
        type: 'expense',
        groupId: GROUP_ID_OPTIONAL,
        colorVariant: 4,
        isDefault: true,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 'rule-default-shopping-electronics',
        name: 'Shopping - Electronics',
        patterns: [
            {
                field: 'payee',
                matchType: 'wordlist',
                words: ['ARVUTITARK', 'KLICK', 'EURONICS', 'ELECTRONICS', 'TECHNIKA'].map(text => ({
                    text,
                    negated: false
                })),
                caseSensitive: false,
                weight: 10,
            },
        ],
        patternLogic: 'OR',
        priority: 2,
        type: 'expense',
        groupId: GROUP_ID_OPTIONAL,
        colorVariant: 5,
        isDefault: true,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
];